begin;

alter table public.booking_reservations
  add column if not exists created_at timestamptz default now();

update public.booking_reservations
set created_at = now()
where created_at is null;

alter table public.booking_reservations
  alter column created_at set not null;

update public.booking_reservations
set status = lower(trim(status))
where status is not null;

update public.booking_reservations
set status = 'booked'
where status is null
   or trim(status) = ''
   or lower(trim(status)) not in ('booked', 'tentative', 'pending');

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.booking_reservations'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format('alter table public.booking_reservations drop constraint if exists %I', c.conname);
  end loop;
end $$;

alter table public.booking_reservations
  add constraint booking_reservations_status_check
  check (status in ('booked', 'tentative', 'pending'));

create table if not exists public.agreement_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  storage_path text not null,
  file_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.booking_agreements (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.booking_reservations(id) on delete cascade,
  reservation_date date not null,
  template_id bigint references public.agreement_templates(id) on delete set null,
  template_name text,
  renter_name text,
  renter_email text,
  renter_phone text,
  event_type text,
  agreement_status text not null default 'pending_signature' check (
    agreement_status in ('pending_signature', 'sent', 'viewed', 'awaiting_manager_approval', 'approved', 'completed', 'declined', 'expired', 'voided', 'canceled')
  ),
  opensign_document_id text,
  opensign_draft_url text,
  draft_pdf_url text,
  signed_pdf_url text,
  audit_log_url text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agreement_settings (
  id bigint primary key,
  notify_email text not null,
  venue_signer_email text,
  updated_at timestamptz not null default now()
);

create table if not exists public.agreement_template_fields (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.agreement_templates(id) on delete cascade,
  field_key text not null,
  field_type text not null check (field_type in ('text', 'email', 'phone', 'date', 'signature', 'initial', 'number', 'name', 'checkbox', 'dropdown')),
  signer_role text not null default 'renter' check (signer_role in ('renter', 'venue')),
  is_required boolean not null default true,
  autofill_source text,
  page_number integer not null default 1,
  x numeric(10,2) not null default 0,
  y numeric(10,2) not null default 0,
  width numeric(10,2) not null default 180,
  height numeric(10,2) not null default 34,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create or replace function public.touch_booking_agreements_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

drop trigger if exists trg_touch_booking_agreements_updated_at on public.booking_agreements;
create trigger trg_touch_booking_agreements_updated_at
before update on public.booking_agreements
for each row execute function public.touch_booking_agreements_updated_at();

create index if not exists agreement_templates_created_idx
  on public.agreement_templates (created_at desc);

create index if not exists booking_agreements_status_created_idx
  on public.booking_agreements (agreement_status, created_at desc);

create index if not exists booking_agreements_reservation_idx
  on public.booking_agreements (reservation_id);

create index if not exists agreement_template_fields_template_idx
  on public.agreement_template_fields (template_id, sort_order);

alter table public.agreement_templates enable row level security;
alter table public.booking_agreements enable row level security;
alter table public.agreement_template_fields enable row level security;
alter table public.agreement_settings enable row level security;

drop policy if exists agreement_templates_authenticated_rw on public.agreement_templates;
create policy agreement_templates_authenticated_rw
on public.agreement_templates
for all
to authenticated
using (true)
with check (true);

drop policy if exists booking_agreements_authenticated_rw on public.booking_agreements;
create policy booking_agreements_authenticated_rw
on public.booking_agreements
for all
to authenticated
using (true)
with check (true);

drop policy if exists agreement_template_fields_authenticated_rw on public.agreement_template_fields;
create policy agreement_template_fields_authenticated_rw
on public.agreement_template_fields
for all
to authenticated
using (true)
with check (true);

drop policy if exists agreement_settings_authenticated_rw on public.agreement_settings;
create policy agreement_settings_authenticated_rw
on public.agreement_settings
for all
to authenticated
using (true)
with check (true);

commit;
